spring:
  datasource:
    driver:
      class: com.mysql.jdbc.driver
    password: Miasha@9621
    url: jdbc:mysql://localhost:3306/miashadb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  